### ISSUE TITLE
Answer pre-interview questions

### ISSUE THREAD

**Issue by Nin-ng** [Hack-for-California/GenPlan_AffordableHousing#1]
Ask Professor  or  try to answer some questions intending to ask Dr. Brinkley

What data is available for comparison against the general plan repository utilized in the Mapping Tool?
Who is the target audience(s) for the data analysis report?
What metrics and visualization need do you believe would be meaningful?
What are the timeline restrictions and milestones? 
What region (county or city) do you envision starting with?

**Comment by makharrison** [comment]
Questions were answered.
