### ISSUE TITLE
Create missing housing element folder 

### ISSUE THREAD

**Issue by Nin-ng** [Hack-for-California/GenPlan_AffordableHousing#7]
→ notify other GenPlan group

**Comment by Nin-ng** [comment]
After checking the file Missing data.xlsx, there isn't missing data in the housing element folder.

**Comment by Nin-ng** [comment]
After checking the file Missing data.xlsx, there isn't missing data in the housing element folder.

**Comment by makharrison** [comment]
Closing issue.
